### PR TITLE
Initial pipeline config

### PR DESCRIPTION
**Pull request by LeeTranMN**

### CODE REVIEW

**Comment by LeeTranMN** [comment]
Sorry for all the commits, was testing the pipeline, they'll all go away in a squash merge :)

**Review by chrisgoeden — APPROVED** [review]
Looks good!

**Review by joseph-dasuki — APPROVED** [review]

**Comment by chrisgoeden** [comment]
I see that you added additional files to this PR.  Are you done with your changes to this PR?  I'd like to review again but once you're done with your changes.

**Comment by LeeTranMN** [comment]
> I see that you added additional files to this PR. Are you done with your changes to this PR? I'd like to review again but once you're done with your changes.

Additional changes were just me pushing stuff during a demo, lemme re-fix the tests and then we should be good to go

**Review by chrisgoeden — APPROVED** [review]

**Pull request merged**
